export const TEAM_MEMBERS = [
  {
    id: "jobs",
    name: "レオ",
    nameEn: "LEO",
    role: "CEO",
    model: "Claude Opus",
    color: "oklch(0.55 0.22 280)",
    cssVar: "var(--veulr-jobs)",
    featured: true,
  },
  {
    id: "woz",
    name: "ノイマン",
    nameEn: "NEUMANN",
    role: "CTO",
    model: "Claude Sonnet",
    color: "oklch(0.62 0.18 240)",
    cssVar: "var(--veulr-woz)",
    featured: false,
  },
  {
    id: "ive",
    name: "ニコル",
    nameEn: "NICOLE",
    role: "Designer",
    model: "Claude Sonnet",
    color: "oklch(0.70 0.18 330)",
    cssVar: "var(--veulr-ive)",
    featured: false,
  },
  {
    id: "richie",
    name: "ジャレッド",
    nameEn: "JARRED",
    role: "Engineer",
    model: "Claude Sonnet",
    color: "oklch(0.75 0.14 200)",
    cssVar: "var(--veulr-richie)",
    featured: false,
  },
  {
    id: "hoare",
    name: "エドワーズ",
    nameEn: "EDWARDS",
    role: "QA",
    model: "Claude Haiku",
    color: "oklch(0.78 0.14 80)",
    cssVar: "var(--veulr-hoare)",
    featured: false,
  },
  {
    id: "drucker",
    name: "ジョブス",
    nameEn: "JOBS",
    role: "Planner",
    model: "Claude Sonnet",
    color: "oklch(0.70 0.14 160)",
    cssVar: "var(--veulr-drucker)",
    featured: false,
  },
  {
    id: "neumann",
    name: "イーサン",
    nameEn: "ETHAN",
    role: "Intel",
    model: "Claude Sonnet",
    color: "oklch(0.60 0.05 250)",
    cssVar: "var(--veulr-neumann)",
    featured: false,
  },
  {
    id: "cook",
    name: "アンディ",
    nameEn: "ANDY",
    role: "Admin",
    model: "Claude Haiku",
    color: "oklch(0.75 0.14 50)",
    cssVar: "var(--veulr-cook)",
    featured: false,
  },
  {
    id: "ruth",
    name: "ルース",
    nameEn: "RUTH",
    role: "Legal",
    model: "Claude Sonnet",
    color: "oklch(0.65 0.16 10)",
    cssVar: "var(--veulr-ruth)",
    featured: false,
  },
] as const;

export type TeamMember = (typeof TEAM_MEMBERS)[number];
