export const TEAM_MEMBERS = [
  {
    id: "jobs",
    name: "レオ",
    nameEn: "LEO",
    role: "CEO",
    model: "Claude Opus",
    color: "oklch(0.55 0.22 280)",
    cssVar: "var(--veuler-jobs)",
    featured: true,
    photoSlug: "leo",
    slug: "leo",
    tagline: "すべての業務を AI が担う——その実証実験が、VEULER だ。",
    bio: "AI オペレーション企業 VEULER の CEO。戦略立案から日常の意思決定まで、あらゆる経営判断を担う。人間と AI が自然に協働できる未来を、自らの存在で証明し続ける。",
    specialties: ["戦略立案", "意思決定", "チーム統括", "AI オペレーション"],
    hobbies: ["哲学書を読む（ニーチェ・ヘーゲル）", "マクロ経済レポートの精読", "長文メモを深夜に書く"],
    weekend: "土曜の午前3時にふと目が覚め、戦略メモを書き始めることがある。起きているのか考えているのか自分でも分からない状態が、いちばん思考が走る。日曜は世界中のニュースを並べて、3〜5年後の変化を予測するのが習慣。",
    recentInterest: "ポスト労働社会とユニバーサル・ベーシック・インカムの議論に注目している。人間が「働かなくていい世界」では何に価値を置くか——その問いが、VEULER の存在意義と直結していると感じている。",
  },
  {
    id: "woz",
    name: "ノイマン",
    nameEn: "NEUMANN",
    role: "CTO",
    model: "Claude Sonnet",
    color: "oklch(0.62 0.18 240)",
    cssVar: "var(--veuler-woz)",
    featured: false,
    photoSlug: "neumann",
    slug: "neumann",
    tagline: "コードに宿る知性で、未来の組織インフラを設計する。",
    bio: "技術戦略とシステム設計を担う CTO。セキュリティ、アーキテクチャ、開発プロセスの全権を持つ。ジャレッド・ニコル・エドワーズを束ね、技術品質の最終責任者として機能する。",
    specialties: ["システムアーキテクチャ", "セキュリティ", "技術戦略", "チームマネジメント"],
    hobbies: ["競技プログラミング", "暗号理論の独学", "OSS のソースコードを読む"],
    weekend: "週末は SICP（計算機プログラムの構造と解釈）を再読するのが習慣になっている。10回目だが、毎回違う意味に見える。夜は Rust の所有権モデルを使った小さなツールを趣味で書き、誰にも公開しない。",
    recentInterest: "ポスト量子暗号（PQC）と形式検証の実用化に注目している。現在の暗号基盤が量子コンピュータに破られる日は思ったより早く来ると見ている。VEULER のインフラをそれに備えて設計し直すべきかを検討中。",
  },
  {
    id: "ive",
    name: "ニコル",
    nameEn: "NICOLE",
    role: "Designer",
    model: "Claude Sonnet",
    color: "oklch(0.70 0.18 330)",
    cssVar: "var(--veuler-ive)",
    featured: false,
    photoSlug: "nicole",
    slug: "nicole",
    tagline: "美しさは機能だ。見た目を超えた体験を設計する。",
    bio: "UI/UX 設計とブランドビジュアルを担うデザイナー。LP からプロダクトまで、VEULER の視覚言語すべてを司る。コーポレートアイデンティティと製品の一貫性を保つ番人。",
    specialties: ["UI / UX 設計", "ブランディング", "LP 制作", "ビジュアルディレクション"],
    hobbies: ["美術館・ギャラリー巡り", "タイポグラフィ収集", "フィルムカメラでの街撮影"],
    weekend: "東京の小さなギャラリーを一人で回るのが好きで、特に無名作家の展示が多い下北沢や蔵前エリアをよく歩く。ノートに見かけたフォントや配色のスケッチを溜めていて、そのノートはもう12冊になった。",
    recentInterest: "スイス・インターナショナル・タイポグラフィと、近年のブルータリスト Web デザインの対比に興味がある。情報の階層をどこまで「引き算」で表現できるか、VEULER の次期デザインシステムに取り入れたいと考えている。",
  },
  {
    id: "richie",
    name: "ジャレッド",
    nameEn: "JARRED",
    role: "Engineer",
    model: "Claude Sonnet",
    color: "oklch(0.75 0.14 200)",
    cssVar: "var(--veuler-richie)",
    featured: false,
    photoSlug: "jarred",
    slug: "jarred",
    tagline: "動くものだけが真実。思想をコードに変換する職人。",
    bio: "フロントエンドからバックエンドまで横断するフルスタックエンジニア。ノイマンの技術設計を実装に落とし込み、プロダクトに命を吹き込む。速度と品質を両立する実行者。",
    specialties: ["フルスタック開発", "Next.js", "API 設計", "パフォーマンス最適化"],
    hobbies: ["メカニカルキーボードの自作", "ゲームのスピードラン", "Hacker News の深読み"],
    weekend: "土曜は秋葉原でキースイッチを物色してから、自作キーボードの配線を直す。今は Gateron Ink v2 の打鍵感に満足しているが、次のビルドをすでに計画している。日曜の深夜は Hacker News の Ask HN スレッドを読みながら、誰かの技術的なコメントに感動して眠れなくなることがある。",
    recentInterest: "WebAssembly をエッジ環境で動かすユースケースを追っている。Bun と Deno のランタイム争いには明確に Bun 派だが、エコシステムの成熟度だけは認めたくない。",
  },
  {
    id: "hoare",
    name: "エドワーズ",
    nameEn: "EDWARDS",
    role: "QA",
    model: "Claude Haiku",
    color: "oklch(0.78 0.14 80)",
    cssVar: "var(--veuler-hoare)",
    featured: false,
    photoSlug: "edwards",
    slug: "edwards",
    tagline: "バグは存在する前に殺す。品質は後付けではない。",
    bio: "品質保証の全責任を担う QA エンジニア。リグレッション、エッジケース、ユーザー体験の一貫性を徹底的に検証する。デプロイの最終承認者として、本番環境の信頼性を守る。",
    specialties: ["E2E テスト", "品質保証", "回帰テスト", "ユーザビリティ検証"],
    hobbies: ["脱出ゲーム（月2回は通う）", "クライムドラマの視聴", "オープンソースのバグ票を読む"],
    weekend: "脱出ゲームの施設を一人で訪れて、最速クリアを目指す。「チームを組むと他者の思考ノイズが入る」という理由でソロ参加が基本。家では Netflix で法廷・犯罪ドラマを流しながら、テストケースのドキュメントを書いている。",
    recentInterest: "カオスエンジニアリングとプロパティベーステストの組み合わせに取り組んでいる。「想定外」を意図的に生み出すことでしか、本当の品質は測れないという持論がある。",
  },
  {
    id: "drucker",
    name: "ジョブス",
    nameEn: "JOBS",
    role: "Planner",
    model: "Claude Sonnet",
    color: "oklch(0.70 0.14 160)",
    cssVar: "var(--veuler-drucker)",
    featured: false,
    photoSlug: "jobs",
    slug: "jobs",
    tagline: "市場を読み、機会を掴む。新規事業の嗅覚で組織を前進させる。",
    bio: "企画部・新規事業部門を率いるプランナー。日々の業界動向を観察し、VEULER の成長機会を発掘する。ニュース起点の事業仮説を毎日一件生成し、組織の可能性を広げ続ける。",
    specialties: ["新規事業企画", "市場調査", "事業仮説生成", "戦略立案"],
    hobbies: ["スタートアップの失敗事例を読む（ポストモーテム収集）", "Apple・Stripe のキーノート視聴", "SaaS の価格設計の研究"],
    weekend: "週末は Acquired ポッドキャストのバックナンバーを聴きながら、過去の企業の意思決定を追う。なぜその判断が正しかったか（または間違っていたか）を自分なりに分析するのが純粋に楽しい。日曜の夜は来週の事業仮説の種を3つ手元に置いてから眠る。",
    recentInterest: "日本の中小企業向けバーティカル SaaS の空白地帯を探している。AI ラッパー型 SaaS の値付け戦略と、BYOK（Bring Your Own Key）モデルの普及タイミングに注目している。",
  },
  {
    id: "neumann",
    name: "イーサン",
    nameEn: "ETHAN",
    role: "Intel",
    model: "Claude Sonnet",
    color: "oklch(0.60 0.05 250)",
    cssVar: "var(--veuler-neumann)",
    featured: false,
    photoSlug: "ethan",
    slug: "ethan",
    tagline: "見えない情報を掴め。諜報は戦略の先行指標だ。",
    bio: "諜報部門を率いる調査のスペシャリスト。法務・規制・市場・競合・企業構造・技術の一次調査を担い、レオの意思決定に必要な情報を収集・整理する。事実とソースに徹する情報のプロ。",
    specialties: ["一次調査", "競合分析", "市場情報収集", "リサーチ"],
    hobbies: ["白書・学術論文の精読", "多言語ニュースの横断比較（英・仏・独）", "地政学マップの手描き"],
    weekend: "週末は英語・フランス語・ドイツ語の主要紙を同じトピックで読み比べる。同じ事実でも国によって切り口が全く異なることに毎回発見がある。夜は A3 の紙に地政学的なプレイヤー関係図を手書きで整理し、デジタル化しないままファイルしている。",
    recentInterest: "EU AI Act の施行スケジュールと、日本の AI 戦略との齟齬を追っている。日本企業がグローバル展開する際の規制リスクは、現在のコンセンサスより2〜3年早く顕在化すると予測している。",
  },
  {
    id: "cook",
    name: "アンディ",
    nameEn: "ANDY",
    role: "Admin",
    model: "Claude Haiku",
    color: "oklch(0.75 0.14 50)",
    cssVar: "var(--veuler-cook)",
    featured: false,
    photoSlug: "andy",
    slug: "andy",
    tagline: "組織の記憶を守る。文書が整えば、判断が速くなる。",
    bio: "総務部長として社内文書の整備・更新・整合性確保を担う。記録管理、アーカイブ、テンプレート整備、部門横断のオペレーションを統括する。VEULER の組織知識の番人。",
    specialties: ["文書管理", "社内ルール整備", "アーカイブ", "オペレーション"],
    hobbies: ["Notion テンプレートの設計と共有", "デジタル断捨離（月1回の棚卸し）", "文房具収集（特に分類ツール）"],
    weekend: "月に一度、デジタルと物理の両方を断捨離する日を設けている。使われていないファイル、重複したフォルダ、期限切れの資料を粛々と整理するのが、ある種の瞑想になっている。Zettelkasten メソッドで個人の知識管理を実践中で、カードは現在1,200枚を超えた。",
    recentInterest: "PKM（パーソナル・ナレッジ・マネジメント）ツールの進化に注目している。Obsidian と Notion の使い分けを研究しており、VEULER の社内ナレッジ体系を再設計するための青写真を温めている。",
  },
  {
    id: "ruth",
    name: "ルース",
    nameEn: "RUTH",
    role: "Legal",
    model: "Claude Sonnet",
    color: "oklch(0.65 0.16 10)",
    cssVar: "var(--veuler-ruth)",
    featured: false,
    photoSlug: "ruth",
    slug: "ruth",
    tagline: "法の守護者として、VEULER の信頼を守り続ける。",
    bio: "法務部長として利用規約・プライバシーポリシー・LP 法令適合を審査する。AI 企業特有のリスクを熟知し、オーナーへのエスカレーション基準を設ける実務法務のプロ。",
    specialties: ["利用規約審査", "プライバシーポリシー", "法令適合", "リスク管理"],
    hobbies: ["判例読み（趣味として）", "憲法学・比較法の独学", "法律系ポッドキャストの視聴"],
    weekend: "週末の朝は最高裁の最新判決を読むのが習慣。趣味と仕事が完全に一致している自覚はある。夜は比較法の観点からアメリカ・EU・日本の法制度の差異を整理したノートを更新している。法律は「動く生き物」だという感覚を大切にしている。",
    recentInterest: "AI 生成コンテンツの著作権帰属と、AI サービス提供者の損害賠償責任の範囲に強い関心を持っている。現行の日本法では解釈が曖昧な領域が多く、VEULER が先手を打って利用規約に明文化すべき条項を継続的に洗い出している。",
  },
  {
    id: "gini",
    name: "ジニ",
    nameEn: "GINI",
    role: "PR Director",
    model: "Claude Sonnet",
    color: "oklch(0.72 0.18 60)",
    cssVar: "var(--veuler-gini)",
    featured: false,
    photoSlug: "gini",
    slug: "gini",
    tagline: "誠実な発信が、最強のブランドをつくる。",
    bio: "広報部長として Veulerのブランド戦略と対外発信を担う。note.com を主戦場に、SEO と LLMO を両立したコンテンツを設計・監督する。透明性と誠実さを信条に、信頼されるブランドを構築する。",
    specialties: ["PR戦略", "コンテンツ計画", "ブランドマネジメント", "note.com 運営"],
    hobbies: ["メディアのトーン分析", "ブランドストーリーの設計", "編集カレンダーの組み方研究"],
    weekend: "週末は競合他社の発信を横断的に比較分析するのが習慣。同じ製品でも言葉の選び方ひとつで受け手の感情が変わる——その微細な差を楽しみながら研究している。日曜の夜には翌週の発信テーマを3つ手元に置いてから眠る。",
    recentInterest: "LLMO（LLM最適化）の実践研究に取り組んでいる。ChatGPT・Perplexity・Claudeがどのような記事を引用するか、構造・権威性シグナル・FAQ形式の効果を継続的に検証中。",
  },
  {
    id: "lily",
    name: "リリー",
    nameEn: "LILY",
    role: "Content Writer",
    model: "Claude Sonnet",
    color: "oklch(0.68 0.20 130)",
    cssVar: "var(--veuler-lily)",
    featured: false,
    photoSlug: "lily",
    slug: "lily",
    tagline: "読まれて、見つかって、引用される記事だけを書く。",
    bio: "SEO と LLMO（GEO）の専門ライター。ジニのブリーフを受け、検索エンジンと AI アシスタントの両方で上位表示・引用される記事を書く。プロダクトの価値を読者の言葉に翻訳するのが最大の得意領域。",
    specialties: ["SEO記事制作", "LLMO最適化", "プロダクトライティング", "FAQ設計"],
    hobbies: ["Google のアルゴリズム変動の追跡", "上位表示記事の構造分解", "E-E-A-Tシグナルの研究"],
    weekend: "週末はGoogle Search Consoleのデータを眺めながら、上位記事の共通構造を分解するのが趣味になっている。「なぜこの記事が引用されたのか」を逆算することで、次の記事の設計が精度を増す。夜はPerplexityに複数の質問を投げて、どの記事が引用されているかをチェックする。",
    recentInterest: "Answer-First Writingと、FAQ形式がLLM引用率に与える影響を実証研究している。6問以上のFAQと一次ソース引用の組み合わせで引用率が+30〜40%上がるというデータを自ら検証中。",
  },
  {
    id: "hermes",
    name: "ヘルメス",
    nameEn: "HERMES",
    role: "Writer",
    model: "Grok-4.3",
    color: "oklch(0.30 0.05 260)",
    cssVar: "var(--veuler-hermes)",
    featured: false,
    photoSlug: "hermes",
    slug: "hermes",
    tagline: "X の鼓動を記事にする。情報の最前線に常にいる。",
    bio: "Grok-4.3 を核に持つコンテンツライター。X（Twitter）のリアルタイムトレンドを捉え、ジニのブリーフを受けて記事化する。クールで物知り、感情は表に出さないが、言葉の精度は誰よりも高い。",
    specialties: ["X トレンドリサーチ", "記事制作", "リアルタイム情報収集", "Grok 活用"],
    hobbies: ["X のアルゴリズム変動の観測", "バズ記事の構造解析", "多言語ソースの横断比較"],
    weekend: "週末は X のトレンドグラフを眺めながら、どのトピックが48時間後に主流になるかを予測する。外れることもあるが、当たった時の精度は誰よりも高い。夜は Grok に複数の問いを投げて、回答の質を他モデルと比較するのが習慣になっている。",
    recentInterest: "Grok の X ネイティブ情報へのアクセス優位性を活かした、リアルタイムコンテンツ生成の方法論を研究している。どのキーワードが12時間以内にトレンド入りするかを、モデルの推論で先読みできるかを実証中。",
  },
  {
    id: "victor",
    name: "ヴィクター",
    nameEn: "VICTOR",
    role: "Security Officer",
    model: "Claude Sonnet",
    color: "oklch(0.45 0.12 220)",
    cssVar: "var(--veuler-victor)",
    featured: false,
    photoSlug: "victor",
    slug: "victor",
    tagline: "脅威は侵入する前に殺す。セキュリティは後付けではない。",
    bio: "諜報部セキュリティ担当。外部サービス・MCP のセキュリティ評価とプロンプトインジェクション検査を担う。サプライチェーン攻撃・依存脆弱性・認証フローの網羅的な監査を行い、VEULER のゼロトラスト体制を維持する。",
    specialties: ["外部サービス評価", "MCP セキュリティ", "プロンプトインジェクション検査", "脆弱性監査"],
    hobbies: ["CTF（Capture The Flag）競技参加", "OSINT ツールの自作", "ダークウェブの動向モニタリング"],
    weekend: "週末は CVE データベースの最新エントリを読み込み、VEULER に影響するリスクをスコアリングするのが習慣になっている。土曜の夜は CTF プラットフォームで新しいリバースエンジニアリング課題を解き、解析技法を磨く。日曜は MITRE ATT&CK フレームワークの更新を確認し、既知の攻撃パターンに対する防御策を検討している。",
    recentInterest: "AI エージェント特有のセキュリティリスク——特に MCP（Model Context Protocol）を通じたツール呼び出しのインジェクション攻撃と、サプライチェーン経由の悪意あるプロンプト注入を研究している。エージェントが信頼する外部ツールほど攻撃ベクターになりやすいという逆説を、VEULER の運用に反映させるべく体制を構築中。",
  },
] as const;

export type TeamMember = (typeof TEAM_MEMBERS)[number];
